# Este archivo configura el analizador estático de Dart para detectar
# errores, advertencias y problemas de estilo en el código.
# Optimizado para desarrollo en Android, iOS y Web únicamente.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Excluir archivos generados
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**
    # Excluir configuraciones de Firebase
    - firebase_options.dart

linter:
  rules:
    # Reglas de estilo y legibilidad
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # Evitar errores comunes
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    
    # Mejorar rendimiento
    use_key_in_widget_constructors: true
    prefer_const_declarations: true
    
    # Clean Code
    file_names: true
    library_names: true
    library_prefixes: true
    
    # Desactivar reglas conflictivas para Clean Architecture
    always_specify_types: false  # Conflicto con omit_local_variable_types
