name: prosavis
description: "Prosavis - La plataforma de confianza para contratar servicios locales en Colombia."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  provider: ^6.1.5

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1

  # Navigation
  go_router: ^16.0.0

  # Dependency Injection
  get_it: ^7.6.4

  # Storage
  shared_preferences: ^2.2.2

  # Environment
  flutter_dotenv: ^5.1.0

  # UI Enhancements
  material_symbols_icons: ^4.2719.3
  animations: ^2.0.11
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9

  # Other
  intl: ^0.20.2
  firebase_ai: ^3.0.0
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo Black.ttf
          weight: 900
