name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.1.1

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1

  # Navigation
  go_router: ^13.0.1

  # Dependency Injection
  get_it: ^7.6.4

  # Storage
  shared_preferences: ^2.2.2

  # Environment
  flutter_dotenv: ^5.1.0

  # UI Enhancements
  material_symbols_icons: ^4.2719.3
  animations: ^2.0.11
  shimmer: ^3.0.0

  # Other
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
